In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/iris-flower-dataset/IRIS.csv


In [2]:
iris = pd.read_csv(os.path.join(dirname, filename))

In [3]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
# Various Species Classes are:

iris['species'].value_counts()

Iris-virginica     50
Iris-setosa        50
Iris-versicolor    50
Name: species, dtype: int64

In [5]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [6]:
iris.shape

(150, 5)

### Removing the third class as we are doing Logistic Regression as a binary classifier

In [7]:
iris_df = iris[iris['species'] != 'Iris-virginica']

In [8]:
iris_df['species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Name: species, dtype: int64

In [9]:
# Converting categorical value to numeric value

from sklearn import preprocessing

In [10]:
flower_class = preprocessing.LabelEncoder()
flower_class.fit(['Iris-setosa', 'Iris-versicolor'])
iris_df['species'] = flower_class.transform(iris_df['species'])

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [11]:
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [12]:
iris_df['species'].unique()

array([0, 1])

* <b> We dont neeed any more preprocessing in this case </b>

# Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression

### Train-Test Split

In [14]:
from sklearn.model_selection import train_test_split

x = iris_df[['sepal_length','sepal_width','petal_length','petal_width']]
y = iris_df['species']

In [15]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3,random_state=3)

In [16]:
x_train.shape , x_test.shape

((70, 4), (30, 4))

In [17]:
y_train.shape , y_test.shape

((70,), (30,))

In [18]:
LR = LogisticRegression(C=0.01,solver='liblinear').fit(x_train,y_train)

In [19]:
yhat = LR.predict(x_test)
yhat

array([1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1])

In [20]:
y_test

93    1
67    1
6     0
64    1
96    1
83    1
98    1
42    0
25    0
15    0
77    1
9     0
71    1
97    1
34    0
75    1
82    1
23    0
59    1
45    0
73    1
12    0
8     0
4     0
79    1
86    1
17    0
65    1
47    0
50    1
Name: species, dtype: int64

In [21]:
yhat_prob = LR.predict_proba(x_test)
yhat_prob

array([[0.40272783, 0.59727217],
       [0.37405124, 0.62594876],
       [0.60261908, 0.39738092],
       [0.40610568, 0.59389432],
       [0.36637465, 0.63362535],
       [0.29635531, 0.70364469],
       [0.43066325, 0.56933675],
       [0.60149911, 0.39850089],
       [0.57850524, 0.42149476],
       [0.64726707, 0.35273293],
       [0.31827048, 0.68172952],
       [0.59167606, 0.40832394],
       [0.37982316, 0.62017684],
       [0.3649942 , 0.6350058 ],
       [0.59167606, 0.40832394],
       [0.36398693, 0.63601307],
       [0.38192195, 0.61807805],
       [0.57711601, 0.42288399],
       [0.36989796, 0.63010204],
       [0.58734147, 0.41265853],
       [0.33641691, 0.66358309],
       [0.59313256, 0.40686744],
       [0.58142442, 0.41857558],
       [0.61841448, 0.38158552],
       [0.40967979, 0.59032021],
       [0.34671119, 0.65328881],
       [0.61236791, 0.38763209],
       [0.36925313, 0.63074687],
       [0.59679012, 0.40320988],
       [0.35668714, 0.64331286]])

In [22]:
from sklearn.metrics import confusion_matrix

In [23]:
confusion_matrix(y_test,yhat,labels=[0,1])

array([[13,  0],
       [ 0, 17]])

In [24]:
from sklearn.metrics import accuracy_score

score =accuracy_score(y_test,yhat)
score

1.0

# Support Vector Machine

In [25]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [26]:
# Convert categorical values to numeric values

In [27]:
iris['species'].value_counts()

Iris-virginica     50
Iris-setosa        50
Iris-versicolor    50
Name: species, dtype: int64

In [28]:
iris['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [29]:
flowers = preprocessing.LabelEncoder()
flowers.fit(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
iris['species'] = flowers.transform(iris['species'])

In [30]:
iris['species'].unique()

array([0, 1, 2])

In [31]:
iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species           int64
dtype: object

In [32]:
# Convert the label types to int

iris[['sepal_length','sepal_width','petal_length','petal_width']] = iris[['sepal_length','sepal_width','petal_length','petal_width']].astype('int')

In [33]:
iris.dtypes

sepal_length    int64
sepal_width     int64
petal_length    int64
petal_width     int64
species         int64
dtype: object

In [34]:
x = iris[['sepal_length','sepal_width','petal_length','petal_width']]
y = iris['species']

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=3)

In [36]:
x_train.shape , x_test.shape

((105, 4), (45, 4))

In [37]:
y_train.shape,y_test.shape

((105,), (45,))

In [38]:
from sklearn import svm

In [39]:
clf = svm.SVC(kernel='rbf')
clf.fit(x_train,y_train)
yhat = clf.predict(x_test)

/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [40]:
yhat

array([0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 2, 0, 1, 2, 2, 0, 1, 2,
       2, 1, 0, 2, 2, 1, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0, 2, 1, 2, 1, 0, 0,
       1])

In [41]:
confusion_matrix(y_test,yhat)

array([[17,  0,  0],
       [ 0, 13,  1],
       [ 0,  2, 12]])

In [42]:
from sklearn.metrics import f1_score
f1_score(y_test, yhat, average='weighted') 

0.9332481907194552

In [43]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, yhat)

/opt/conda/lib/python3.6/site-packages/sklearn/metrics/classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.9333333333333333